pipeline {
 agent any
     stages {
         stage('Clone Repository') {
         /* Cloning the repository to our workspace */
         steps {
         checkout scm
         }
    }
    stage('Build Image') {
         steps {
         sh 'sudo docker build -t nirdeshkumar02/webapp:hello_world_app .'
         }
    }
    stage('Run Image') {
         steps {
         sh 'sudo docker run -d -p 5000:5000 --name hello_world nirdeshkumar02/webapp:hello_world_app'
         }
    }
    stage('Testing'){
         steps {
             echo 'Testing..'
             }
    }
  }
}
